// Copyright vfcastr 2025
// SPDX-License-Identifier: MPL-2.0

package events

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	log "github.com/sirupsen/logrus"
	"github.com/vfcastr/Zabbix-MCP/pkg/client"
	"github.com/vfcastr/Zabbix-MCP/pkg/utils"
)

type Event struct {
	EventID      string       `json:"eventid"`
	Source       string       `json:"source"`
	Object       string       `json:"object"`
	ObjectID     string       `json:"objectid"`
	Clock        string       `json:"clock"`
	Name         string       `json:"name"`
	Value        string       `json:"value"`
	Severity     string       `json:"severity"`
	Acknowledged string       `json:"acknowledged"`
	Suppressed   string       `json:"suppressed"`
	OpData       string       `json:"opdata"`
	Tags         []client.Tag `json:"tags,omitempty"`
}

type EventGetParams struct {
	Output             interface{} `json:"output,omitempty"`
	EventIDs           []string    `json:"eventids,omitempty"`
	GroupIDs           []string    `json:"groupids,omitempty"`
	HostIDs            []string    `json:"hostids,omitempty"`
	ObjectIDs          []string    `json:"objectids,omitempty"`
	Source             *int        `json:"source,omitempty"`
	Object             *int        `json:"object,omitempty"`
	Acknowledged       *bool       `json:"acknowledged,omitempty"`
	Suppressed         *bool       `json:"suppressed,omitempty"`
	Severities         []int       `json:"severities,omitempty"`
	TimeFrom           int64       `json:"time_from,omitempty"`
	TimeTill           int64       `json:"time_till,omitempty"`
	SelectHosts        interface{} `json:"selectHosts,omitempty"`
	SelectTags         interface{} `json:"selectTags,omitempty"`
	SelectAcknowledges interface{} `json:"selectAcknowledges,omitempty"`
	SortField          []string    `json:"sortfield,omitempty"`
	SortOrder          []string    `json:"sortorder,omitempty"`
	Limit              int         `json:"limit,omitempty"`
}

func GetEvents(logger *log.Logger) server.ServerTool {
	return server.ServerTool{
		Tool: mcp.NewTool("get_events",
			mcp.WithToolAnnotation(mcp.ToolAnnotation{IdempotentHint: utils.ToBoolPtr(true)}),
			mcp.WithDescription("Retrieve events generated by triggers, network discovery and other Zabbix systems."),
			mcp.WithString("eventids", mcp.Description("Comma-separated list of event IDs to filter by")),
			mcp.WithString("groupids", mcp.Description("Comma-separated list of host group IDs to filter by")),
			mcp.WithString("hostids", mcp.Description("Comma-separated list of host IDs to filter by")),
			mcp.WithString("objectids", mcp.Description("Comma-separated list of object IDs (e.g., trigger IDs) to filter by")),
			mcp.WithNumber("source", mcp.Description("Event source: 0=trigger, 1=discovery, 2=autoregistration, 3=internal, 4=service")),
			mcp.WithNumber("object", mcp.Description("Event object type: 0=trigger, 1=discovered host, 2=discovered service, 3=autoregistration, 4=item, 5=LLD rule, 6=service")),
			mcp.WithBoolean("acknowledged", mcp.Description("Filter by acknowledged status")),
			mcp.WithString("severities", mcp.Description("Comma-separated list of severities (0-5)")),
			mcp.WithNumber("time_from", mcp.Description("Return only events after this Unix timestamp")),
			mcp.WithNumber("time_till", mcp.Description("Return only events before this Unix timestamp")),
			mcp.WithNumber("limit", mcp.Description("Max events to return (default: 100)")),
		),
		Handler: func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return getEventsHandler(ctx, req, logger)
		},
	}
}

func getEventsHandler(ctx context.Context, req mcp.CallToolRequest, logger *log.Logger) (*mcp.CallToolResult, error) {
	zabbix, err := client.GetZabbixClientFromContext(ctx, logger)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("Failed to get Zabbix client: %v", err)), nil
	}

	params := EventGetParams{
		Output:     "extend",
		SelectTags: "extend",
		SortField:  []string{"clock", "eventid"},
		SortOrder:  []string{"DESC", "DESC"},
		Limit:      100,
	}

	if args, ok := req.Params.Arguments.(map[string]interface{}); ok && args != nil {
		if v, ok := args["eventids"].(string); ok && v != "" {
			params.EventIDs = splitAndTrim(v)
		}
		if v, ok := args["groupids"].(string); ok && v != "" {
			params.GroupIDs = splitAndTrim(v)
		}
		if v, ok := args["hostids"].(string); ok && v != "" {
			params.HostIDs = splitAndTrim(v)
		}
		if v, ok := args["objectids"].(string); ok && v != "" {
			params.ObjectIDs = splitAndTrim(v)
		}
		if v, ok := args["source"].(float64); ok {
			src := int(v)
			params.Source = &src
		}
		if v, ok := args["object"].(float64); ok {
			obj := int(v)
			params.Object = &obj
		}
		if v, ok := args["acknowledged"].(bool); ok {
			params.Acknowledged = &v
		}
		if v, ok := args["severities"].(string); ok && v != "" {
			params.Severities = parseSeverities(v)
		}
		if v, ok := args["time_from"].(float64); ok && v > 0 {
			params.TimeFrom = int64(v)
		}
		if v, ok := args["time_till"].(float64); ok && v > 0 {
			params.TimeTill = int64(v)
		}
		if v, ok := args["limit"].(float64); ok && v > 0 {
			params.Limit = int(v)
		}
	}

	result, err := zabbix.Call("event.get", params)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("Failed to get events: %v", err)), nil
	}

	var events []Event
	json.Unmarshal(result, &events)
	jsonData, _ := json.MarshalIndent(events, "", "  ")
	return mcp.NewToolResultText(string(jsonData)), nil
}

func splitAndTrim(s string) []string {
	var result []string
	for _, part := range strings.Split(s, ",") {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

func parseSeverities(s string) []int {
	var result []int
	for _, part := range strings.Split(s, ",") {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			var severity int
			fmt.Sscanf(trimmed, "%d", &severity)
			if severity >= 0 && severity <= 5 {
				result = append(result, severity)
			}
		}
	}
	return result
}
